kind = "api"
previewPath = "/"
title = "Emerald AI"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3000
name = "Emerald AI"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace/emerald-ai && node index.js"

[services.production]

[services.production.build]
args = ["sh", "-c", "cd emerald-ai && npm install --omit=dev"]

[services.production.run]
args = ["node", "emerald-ai/index.js"]

[services.production.run.env]
PORT = "3000"
NODE_ENV = "production"
