// Server-side twin of downloadClientReport() in emerald-web's home.tsx: turns
// the full ("restricted") report HTML into the Client View — no Executive
// Summary / Action Matrix, no SENTINEL notes, badge flipped to CLIENT VIEW and
// the section eyebrows renumbered. Kept string-based (the report markup is
// generated by us and its sections/notes never nest) to avoid an HTML-parser
// dependency; keep the two implementations in step.

// Remove the element whose opening tag matches `open`, through its balanced
// closing tag. Handles same-tag nesting (e.g. divs inside a note).
function removeElement(html: string, open: RegExp, tag: string): string {
  const m = open.exec(html);
  if (!m) return html;
  const tagRe = new RegExp(`<(/?)${tag}\\b[^>]*>`, "gi");
  tagRe.lastIndex = m.index;
  let depth = 0;
  let end = -1;
  for (let t = tagRe.exec(html); t; t = tagRe.exec(html)) {
    depth += t[1] ? -1 : 1;
    if (depth === 0) { end = t.index + t[0].length; break; }
  }
  if (end < 0) return html;
  return html.slice(0, m.index) + html.slice(end);
}

function removeAll(html: string, open: RegExp, tag: string): string {
  let prev: string;
  do { prev = html; html = removeElement(html, open, tag); } while (html !== prev);
  return html;
}

export function toClientView(html: string): string {
  let out = html;

  out = removeAll(out, /<section\b[^>]*\bid="actions"[^>]*>/i, "section");
  out = removeAll(out, /<section\b[^>]*\bid="exec"[^>]*>/i, "section");
  out = removeAll(out, /<div\b[^>]*\bclass="[^"]*\bsentinel-note\b[^"]*"[^>]*>/i, "div");

  // Nav links to the removed sections, plus any group label left empty.
  out = out.replace(/<a\b[^>]*\bhref="#(?:exec|actions)"[^>]*>[\s\S]*?<\/a>/gi, "");
  out = out.replace(
    /<div class="nav-lbl">[^<]*<\/div>\s*(?=<div class="nav-lbl">|<\/nav>|<\/aside>|<\/div>\s*<\/aside>)/gi,
    "",
  );

  // Badge: RESTRICTED -> CLIENT VIEW (two-line badge, or the old single string).
  out = out.replace(/(<span class="bt-type">)RESTRICTED(<\/span>)/, "$1CLIENT VIEW$2");
  out = out.replace(/(id="reportTypeBadge"[^>]*>)RESTRICTED/, "$1CLIENT VIEW");
  out = out.replace(/(<div\b[^>]*\bclass="badge-type)(")([^>]*\bid="reportTypeBadge")/, "$1 client$2$3");

  // Renumber the remaining section eyebrows sequentially.
  let n = 0;
  out = out.replace(/(<[a-z0-9]+\b[^>]*\bclass="se"[^>]*>)\s*Section\s+[^\s<]+/gi, (_m, open: string) => {
    n += 1;
    return `${open}Section ${String(n).padStart(2, "0")}`;
  });

  return out;
}
