// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ui-variants/Cinematic.tsx": () => import("../components/mockups/ui-variants/Cinematic.tsx"),
  "./components/mockups/ui-variants/Motion.tsx": () => import("../components/mockups/ui-variants/Motion.tsx"),
  "./components/mockups/ui-variants/Refined.tsx": () => import("../components/mockups/ui-variants/Refined.tsx")
};
